### ISSUE TITLE
Package an example model

### ISSUE THREAD

**Issue by cmutel** [pjamesjoyce/lcopt#11]
This wouldn't need to build off of e.g. ecoinvent - it could be completely self-contained - but this would be a huge help in getting people started.

**Comment by pjamesjoyce** [comment]
I've packaged 2 versions of an example model - one for ecoinvent enabled users and one for forwast users. 

The lcopt-launcher script now checks which databases you have set up and launches the correct version when you click on the new 'Open Example Model' button (defaulting to ecoinvent if you have both). If you have neither it disables the example button and warns you that you need to set up the databases.

![lcopt_launcher](https://user-images.githubusercontent.com/11718809/29569451-dd63a73a-8753-11e7-8dc9-fb22bd1dde32.JPG)

I thought about making it self-contained but I can't figure out a way to do it that wouldn't require a third version of the bw2 setup script to either just set up the biosphere exchanges or the biosphere plus a database with a bunch of dummy technosphere processes in so the user could link external inputs. I went with the auto-choosing 2 version approach as a compromise.

**Comment by pjamesjoyce** [comment]
Link this issue to openjournals/joss-reviews#339
