### ISSUE TITLE
If I have an existing project in Brightway, can I display it in lcopt?

### ISSUE THREAD

**Issue by xiaoshir** [pjamesjoyce/lcopt#14]
I have watched the intro video for  lcopt, and feel quite excited about it. I see lcopt as a tool to build foreground lca model, but I have an existing project in Brightway, and wonder if I can display it in lcopt to have an overview of my foreground lci flows?

I initially imported my foreground inventory to Brightway through excel sheet, but it is really hard to have an overview of what's in there. It would be great if an activity and its amount are specified, its foreground upstream processes can be displayed in lcopt. I hope to see all the foreground activities and their linkages to background datasets for the first time (i.e. no need to show how background datasets are further linked with other background datasets). Is that something that can be achieved in lcopt? @pjamesjoyce 

See attached for:
- a script that imports a foreground database in excel, and links it with background database
- foreground inventories in excel

Thanks in advance!
[example.zip](https://github.com/pjamesjoyce/lcopt/files/1380658/example.zip)

**Comment by pjamesjoyce** [comment]
Hi @xiaoshir 

In short, yes you can, but not in the release version of lcopt.

I've added a couple of experimental features to a development branch (07937b6), one of which is the ability to import bw2package files into lcopt.

To import your model you'll need to install the development version of lcopt. To do this you need to overwrite your current version with the development version like so :

```
pip install --ignore-installed https://github.com/pjamesjoyce/lcopt/archive/development.zip
```

Once you've got this version installed you need to export your brightway model as a `.bw2package` file, then import this `.bw2package` into lcopt using the new function 
```python
model = create_LcoptModel_from_BW2Package(bw2_package_path)
```
I've attached an extended version of your notebook which goes through all of your steps to create the model from the excel file, then creates the bw2package and the lcopt model.

Here's the attachment : [example_JJ.zip](https://github.com/pjamesjoyce/lcopt/files/1382335/example_JJ.zip)


The folder also contains the `.lcopt` model file that I created from your excel file.

A couple of things to note:

The default layout of the flow sheet after you import it isn't very good - it just staggers the unit processes and the inputs in order. It takes a bit of patience to drag the boxes into a more sensible layout, but it's possible - see picture. Also worth noting that if a box starts outside of the 'canvas', as soon as you start to drag it it'll 'jump' back into the canvas, which is quite annoying. I'll aim to fix this at some point.

![lcopt_layout](https://user-images.githubusercontent.com/11718809/31540656-869b74aa-b00c-11e7-8959-19f9efd67c53.jpg)

The `.lcopt` file should contain the fixed layout. I've also included a json file in the zip file which codes the fixed layout - there are instructions in the notebook on how to use it.

The analysis runs ok on the model I've created. One thing to note - lcopt needs all of the unit processes to have 1 unit of output, so the import routine normalises any processes where the production amount isn't 1 to 1. This means the inputs to your packaging process has been normalised.

If you have any questions give me a shout, either on here or at pjjoyce@kth.se

**Comment by xiaoshir** [comment]
Ah.....this is so cool and I love it! Two further questions:
1.  "The default layout of the flow sheet after you import it isn't very good."
- Expected and understandable. But do you think if there is any way to make the default layout look better? 
2. "One thing to note - lcopt needs all of the unit processes to have 1 unit of output, so the import routine normalises any processes where the production amount isn't 1 to 1. This means the inputs to your packaging process has been normalised." 
- I would prefer it accepts unit process amount of other values. Is it possible? The reason is, I find restructuring of datasets quite common when I do LCA due to contribution analysis. After restructuring, it is common that I have unit process production amount of not equal to 1. Of course, I can do this, but it is just one more step. I think mathematically it doesn't make a difference, and I know unit process production amount of not equal to 1 is acceptable in Brightway as long as it is specified under Exchanges in the import file.
