### ISSUE TITLE
Try and find a quicker alternative to `recurse_tagged_database`

### ISSUE THREAD

**Issue by pjamesjoyce** [pjamesjoyce/lcopt#25]
[`presamples`](https://github.com/PascalLesage/brightway2-presamples) makes recalculating brightway `LCA` objects with different methods and parameter sets lightning fast.

The full analysis calculation still drags because of the need to explore the whole graph for each method for each parameter set e.g. from recent project: 
- 18 methods, 6 parameter sets = 108 calculations
- time to calculate LCA/LCI/LCIA x 108 with `presamples` = 1.5 seconds
- time to run lcopt analysis = 2 min 40 seconds

Maybe look into exploring the whole foreground graph once then recharacterising the tagged groups per method? (groups don't change between iterations)

**Comment by pjamesjoyce** [comment]
Benchmark analysis time down to 2 minutes with new analysis setup  - it's a start - 25% faster...

**Comment by pjamesjoyce** [comment]
Slightly new approach to the analysis step

Benchmark analysis is down to 1 min 8 seconds - more than twice as fast as before.

### Details in brief

- new functions editing `bw2analyzer.traverse_tagged_databases`, `bw2analyzer.aggregate_tagged_graph` and `bw2analyzer.recurse_tagged_database` to allow multiple methods to be used in one run, and to allow secondary tags to be applied to graph nodes

    *The graph returned is the same except the `impact` key in `technosphere`/`biosphere` becomes a list with `n` elements (where `n` in the number of methods used).*
    *When aggregated, the value in the dictionary is also now a list with one sum per method.*

- new function `multi_traverse_tagged_databases` only needs to run once (for all methods) instead of multiple times (once per method). This saves a bit of time (~25% faster).
    
- addition of secondary tags means that the tree can be tagged by `name` (for aggregation of foreground results) and by `lcopt_type` (for tree/bullseye/mass flow visualisations) in one run, instead of having to run tagging by type, then run tagging by name. This saves a lot of time as the analysis only needs to run once, not twice.

@cmutel: If you think that a version of the tagged analysis that can use multiple methods and has secondary tags would be useful for `bw2analyzer` proper I'm happy to write them up as a pull request (with the proper tests etc.)

**Comment by cmutel** [comment]
@pjamesjoyce Yes, please do!
