### ISSUE TITLE
Can't perform LCA

### ISSUE THREAD

**Issue by brezen90** [pjamesjoyce/lcopt#34]
I am a new user of Python, Brightway and Lcopt; so forgive me if I make silly mistakes!

I have just installed lcopt in anaconda and followed all the steps detailed on the website. However, when I open lcopt and I try to obtain LCA results (whether I use the ready made example or a new process), I receive: 500: Server Error.

In the Anaconda Prompy, it says: 
Exchange between ('Ecoinvent3_3_cutoff', 'b80c575f22df17a0fbc7b4ae11f65dd2') and ('Example Model_Database', '44bff8eb4556de1742af8dfc669016bb') is invalid - one of these objects is unknown (i.e. doesn't exist as a process dataset)

What did I do wrong? Could you please help?

**Comment by pjamesjoyce** [comment]
Hi @brezen90,

The first thing to check is whether you've set it up with the correct version of ecoinvent.

lcopt is only currently compatible with the ecoinvent 3.3 **cutoff** database. If you've set it up with another version of ecoinvent (e.g. 3.3 APOS or 3.4 cutoff) it won't function properly. I'm in the process of figuring out how to allow different versions of ecoinvent to be used at the moment, but the example model uses 3.3 cutoff.

Try the steps outlined here: https://github.com/pjamesjoyce/lcopt/issues/23

Let me know if that works.

If you are using the right version of ecoinvent, it's something new...

**Comment by brezen90** [comment]
I see. I was actually using the ecoinvent 3.4 cutoff database!

That would be very convenient if lcopt could work with different versions of the ecoinvent database. Anyway, thank you for the great work. I think lcopt has great potential.
