### ISSUE TITLE
Look into compatability with different ecoinvent versions 

### ISSUE THREAD

**Issue by pjamesjoyce** [pjamesjoyce/lcopt#35]
Getting `eidl` incorporated (#29) would make this a lot easier for the user.

Would need to set up multiple base projects to retain the speed of project creation - maybe just tell people this in the docs

**Comment by pjamesjoyce** [comment]
Might need this to be added to eidl (https://github.com/haasad/EcoInventDownLoader/pull/5) or put a forked version on conda in the meantime

**Comment by haasad** [comment]
https://github.com/haasad/EcoInventDownLoader/pull/5 is merged now

**Comment by pjamesjoyce** [comment]
Started new branch [multiple_ecoinvent_versions](https://github.com/pjamesjoyce/lcopt/tree/multiple_ecoinvent_versions)

**Comment by pjamesjoyce** [comment]
New branch merged
