### ISSUE TITLE
[Question] Use of waterfall charts and bulleye in notebook

### ISSUE THREAD

**Issue by ntropy-esa** [pjamesjoyce/lcopt#70]
Quick question: is it possible to plot in a Jupyter notebook the nice waterfall and bulleye charts which are available in lcopt's gui?

More details: I have an own foreground database, with tags, and I have already the results after traversal, by using these lines 

`
multi_foreground_result, multi_foreground_graph = analysis.multi_traverse_tagged_databases(fu, methods, 
                                                                                  label="tag", default_tag="other", 
                                                                                  secondary_tags=[])

recursed_graph = analysis.get_cum_impact(analysis.deepcopy(multi_foreground_graph[0]))
dropped_graph = analysis.drop_pass_through_levels(analysis.deepcopy(multi_foreground_graph[0]))
mass_flow = analysis.recurse_mass(multi_foreground_graph[0], True)

result_set = {
        'methods': [str(method) for method in methods],
        'units': method_units,
        'scores': scores,
        'foreground_results': multi_foreground_result,
        'graph': recursed_graph,
        'dropped_graph': dropped_graph,
    }
`

e.g.  foreground_results (bulleye, not for negative values, I know)

`
defaultdict(int,
            {'other': [0.0],
             'pyr': [4707.940625048752],
             'biochar_sequestration': [-25136.06337264426],
             'el. heater': [1161.1548859974791]})
`

From what I have seen in the lcopt code, the waterfall charts and bulleye are js scripts.

Related issue #38

**Comment by pjamesjoyce** [comment]
Hi @ntropy-esa

The short answer is no, as you've spotted they're js scripts that run as part of the browser gui. 

The slightly longer answer is that it would be great if you could do this. I'm on parental leave at the moment, until October, but I'll look at this when I'm back. 

In the meantime, for the waterfall chart at least I've got a mini html program you can run from a python Httpserver which I hacked together to make figures for a publication. You copy and paste results into a text box and it draws the charts. It's useful for changing names, order etc.

If you email me at pjjoyce@kth.se I can send it to you.

You (or someone else) might be able to hack together something similar for the bullseye chart. Like I say though, I'll put some proper effort into it when I get back to work.

**Comment by ntropy-esa** [comment]
I had to find a quick fix for a workshop, so I used your piece of code [https://gist.github.com/pjamesjoyce/5509518c138d59f1c40203d1f542da85](here) and added a simple slider, for educational purposes:

`<div id="slider">

    Grid EF: <input type="range" name="rangeInput" min="0" max="1200" onchange="updateTextInput(this.value);">
    <input type="text" id="textInput" value="" onchange="updateTextInput(this.value);">
    
</form>
<script>`

`function updateTextInput(val) {
          document.getElementById('waterfall').innerHTML='';
          document.getElementById('textInput').value=val;
            var EF_el = val/1000;
            var original_data = [
                                { name :"Pellet production", value : 4.6},
                                { name :"Pyrolysis electricity",value : 7.7*EF_el},
                                { name :"Electrical heating",value : 31.2*EF_el},
                                { name :"Biochar C sequestration",value :-26.5}];
            console.log(EF_el);
            console.log(original_data); 
     // rest of the code to display waterfall chart
}
`
