### ISSUE TITLE
LCI data not working

### ISSUE THREAD

**Issue by SamXHu** [pjamesjoyce/lcopt#71]
Hi James, 

I can find the LCI data I am looking for "market for road maintenance" but I can't press the OK button to proceed. Any thoughts on this? Thank you.

**Comment by pjamesjoyce** [comment]
Hi @SamXHu 

I think what's happening is you're only getting one result for your search. In this case you still need to 'choose' that result by clicking on it (it will highlight in blue) before clicking OK.

PS. Sorry for the late response, I'm on parental leave until mid-October - I'll be quicker to respond after that!

**Comment by SamXHu** [comment]
Hi James,

Thanks for your reply.

Actually, I am getting multiple results. But, some of them can be selected while others may not.

Anyway, congratulations! I had my little one on March. Enjoy the time with your newborn. 

Best regards,
Sam
