### ISSUE TITLE
lcopt_launcher.py should be installed by default

### ISSUE THREAD

**Issue by cmutel** [pjamesjoyce/lcopt#8]
This is pretty easy to do; should be something like this in `setup.py`:
`entry_points = {'console_scripts': ['lcopt-launcher = lcopt.bin.lcopt_launcher:main',]}`
See Ocelot for a complete example.

**Comment by pjamesjoyce** [comment]
Excellent - I didn't previously know how to do that. 
I've also added entry points for the two bw2 setup utilities and updated the docs accordingly.

**Comment by pjamesjoyce** [comment]
Link this issue to openjournals/joss-reviews#339
